export const ENDPOINTS = {
  auth: {
    companyRegister: '/auth/company/register',
    companyLogin: '/auth/company/login',
    schoolLogin: '/auth/school/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  schools: {
    list: '/schools',
    byId: (id: string) => `/schools/${id}`,
  },
  academicYears: {
    list: '/academic-years',
    current: '/academic-years/current',
    byId: (id: string) => `/academic-years/${id}`,
    setCurrent: (id: string) => `/academic-years/${id}/set-current`,
  },
  classes: {
    list: '/classes',
    byId: (id: string) => `/classes/${id}`,
  },
  sections: {
    list: '/sections',
    byId: (id: string) => `/sections/${id}`,
  },
  subjects: {
    list: '/subjects',
    byId: (id: string) => `/subjects/${id}`,
  },
  students: {
    list: '/students',
    byId: (id: string) => `/students/${id}`,
    parents: (studentId: string) => `/students/${studentId}/parents`,
    parentById: (studentId: string, parentId: string) => `/students/${studentId}/parents/${parentId}`,
    documents: (studentId: string) => `/students/${studentId}/documents`,
    documentById: (studentId: string, docId: string) => `/students/${studentId}/documents/${docId}`,
  },
  subscriptions: {
    list: '/subscriptions',
    my: '/subscriptions/my',
    byId: (id: string) => `/subscriptions/${id}`,
    cancel: (id: string) => `/subscriptions/${id}/cancel`,
    payments: (id: string) => `/subscriptions/${id}/payments`,
  },
  attendance: {
    base: '/attendance',
    byId: (id: string) => `/attendance/${id}`,
    daily: '/attendance/daily',
    monthly: '/attendance/monthly',
    defaulters: '/attendance/defaulters',
    export: '/attendance/export',
    studentHistory: (studentId: string) => `/attendance/students/${studentId}`,
    studentSummary: (studentId: string) => `/attendance/students/${studentId}/summary`,
    bySection: (sectionId: string) => `/attendance/classSection/${sectionId}`,
    bySectionDate: (sectionId: string, date: string) => `/attendance/classSection/${sectionId}/date/${date}`,
  },
  staff: {
    list: '/staff',
    bulkTemplate: '/staff/bulk/template',
    bulkImport: '/staff/bulk/import',
    bulkStatus: (jobId: string) => `/staff/bulk/status/${jobId}`,
    byId: (id: string) => `/staff/${id}`,
    offboard: (id: string) => `/staff/${id}/offboard`,
    reonboard: (id: string) => `/staff/${id}/reonboard`,
  },
  invite: {
    verifyToken: '/invite/verify-token',
    resend: (userId: string) => `/invite/resend/${userId}`,
  },
  exams: {
    list: '/exams',
    byId: (id: string) => `/exams/${id}`,
    policy: '/exam-policy',
    policyById: (id: string) => `/exam-policy/${id}`,
    timetable: '/exam-timetable',
    timetableById: (id: string) => `/exam-timetable/${id}`,
    students: '/exam-students',
    registerStudents: '/exam-students/register',
    studentEligibility: (examId: string, studentId: string) => `/exam-students/eligibility/${examId}/${studentId}`,
    studentById: (id: string) => `/exam-students/${id}`,
    rooms: '/exam-rooms',
    roomById: (id: string) => `/exam-rooms/${id}`,
    seating: '/exam-seating',
    seatingAutoGenerate: '/exam-seating/auto-generate',
    seatingById: (id: string) => `/exam-seating/${id}`,
    admitCards: '/admit-cards',
    admitCardGenerate: '/admit-cards/generate',
    admitCardGenerateClass: '/admit-cards/generate-class',
    admitCardStudent: '/admit-cards/student',
    admitCardPreview: '/admit-cards/preview',
    admitCardClass: '/admit-cards/class',
    marks: '/exam-marks',
    marksBulk: '/exam-marks/bulk',
    remarks: '/teacher-remarks',
    markSheetStudent: (studentId: string) => `/mark-sheet/student/${studentId}`,
    markSheetClass: '/mark-sheet/class',
    markSheetStudentAnnual: (studentId: string) => `/mark-sheet/student/${studentId}/annual`,
    markSheetClassAnnual: '/mark-sheet/class/annual',
  },
  parent: {
    list: '/parent',
    bulkTemplate: '/parent/bulk/template',
    bulkImport: '/parent/bulk/import',
    bulkStatus: (jobId: string) => `/parent/bulk/status/${jobId}`,
    studentDetail: (id: string) => `/parent/student-detail/${id}`,
    byId: (id: string) => `/parent/${id}`,
    linkStudent: (id: string, studentId: string) => `/parent/${id}/link-student/${studentId}`,
  },
};
