export const ACADEMIC_YEARS_PAGE = {
  title: 'Academic Years',
  description: 'Manage school academic years',
  addButton: 'Add Academic Year',
  table: {
    name: 'Name',
    sessionCode: 'Session Code',
    timetableSession: 'Timetable Session',
    startDate: 'Start Date',
    endDate: 'End Date',
    status: 'Status',
    actions: 'Actions',
  },
  empty: 'No academic years yet. Create one to get started.',
  setCurrentButton: 'Set Current',
  status: {
    current: 'Current',
    inactive: 'Inactive',
    enabled: 'Enabled',
    disabled: 'Disabled',
  },
  form: {
    createTitle: 'Add Academic Year',
    editTitle: 'Edit Academic Year',
    name: 'Name *',
    sessionCode: 'Session Code',
    timetableSession: 'Timetable Session *',
    startDate: 'Start Date *',
    endDate: 'End Date *',
    description: 'Description',
    isEnabled: 'Enabled',
    isActiveSeason: 'Active Session',
    submit: 'Create',
    update: 'Save Changes',
    cancel: 'Cancel',
  },
  placeholders: {
    name: 'Enter Name',
    sessionCode: 'Enter Batch Code',
    timetableSession: 'Select Timetable Session',
    startDate: 'Enter Start Date',
    endDate: 'Enter End Date',
    description: 'Enter Description',
  },
} as const;
