export const APP = {
  name: 'School ERP',
  tagline: 'Sign in to your account',
} as const;

export const STORAGE_KEYS = {
  accessToken: 'auth:access_token',
  refreshToken: 'auth:refresh_token',
  context: 'auth:context',
  isAuthenticated: 'auth:is_authenticated',
  user: 'auth:user',
} as const;

export const ROUTES = {
  root: '/',
  login: '/login',
  signup: '/signup',
  setupPassword: '/setup-password',
  // Super admin routes
  dashboard: '/dashboard',
  schools: '/schools',
  subscriptions: '/subscriptions',
  // School admin routes
  schoolDashboard: '/dashboard',
  academicYears: '/school/academic-years',
  academicYearNew: '/school/academic-years/new',
  academicYearEdit: (id: string) => `/school/academic-years/${id}/edit`,
  classes: '/school/classes',
  classNew: '/school/classes/new',
  classEdit: (id: string) => `/school/classes/${id}/edit`,
  classDetailNew: '/school/class-details/new',
  classDetailEdit: (id: string) => `/school/class-details/${id}/edit`,
  departments: '/school/departments',
  departmentNew: '/school/departments/new',
  departmentEdit: (id: string) => `/school/departments/${id}/edit`,
  roles: '/school/roles',
  subjects: '/school/subjects',
  subjectNew: '/school/subjects/new',
  subjectEdit: (id: string) => `/school/subjects/${id}/edit`,
  syllabus: '/school/syllabus',
  syllabusNew: '/school/syllabus/new',
  syllabusEdit: (id: string) => `/school/syllabus/${id}/edit`,
  materials: '/school/materials',
  materialsNew: '/school/materials/new',
  materialsEdit: (id: string) => `/school/materials/${id}/edit`,
  homework: '/school/homework',
  homeworkNew: '/school/homework/new',
  homeworkEdit: (id: string) => `/school/homework/${id}/edit`,
  timetable: '/school/timetable',
  timetableNew: '/school/timetable/new',
  timetableView: (id: string) => `/school/timetable/${id}`,
  timetableEdit: (id: string) => `/school/timetable/${id}/edit`,
  timetableEmployee: '/school/timetable/employee',
  timetableSession: '/school/timetable/session',
  students: '/students',
  studentDetail: (id: string) => `/students/${id}`,
  staffs: '/staffs',
  staffNew: '/staffs/create-new',
  staffView: (_id: string, name: string) => `/staffs/${name.toLowerCase().trim().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')}`,
  staffEdit: (_id: string, name: string) => `/staffs/${name.toLowerCase().trim().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '')}?edit=true`,
  parents: '/parents',
  financeSetup: '/finance/setup',
  financeLedger: '/finance/ledger',
  salary: '/hr/salary',
} as const;
