export const APP = {
  name: 'School ERP',
  tagline: 'Sign in to your account',
} as const;

export const STORAGE_KEYS = {
  accessToken: 'auth:access_token',
  refreshToken: 'auth:refresh_token',
  context: 'auth:context',
  isAuthenticated: 'auth:is_authenticated',
  user: 'auth:user',
} as const;

export const ROUTES = {
  root: '/',
  login: '/login',
  signup: '/signup',
  setupPassword: '/setup-password',
  // Super admin routes
  dashboard: '/dashboard',
  schools: '/schools',
  subscriptions: '/subscriptions',
  // School admin routes
  schoolDashboard: '/dashboard',
  academicYears: '/school/academic-years',
  academicYearNew: '/school/academic-years/new',
  academicYearEdit: (id: string) => `/school/academic-years/edit?id=${id}`,
  classes: '/school/classes',
  classNew: '/school/classes/new',
  classEdit: (id: string) => `/school/classes/edit?id=${id}`,
  roles: '/school/roles',
  subjects: '/school/subjects',
  subjectNew: '/school/subjects/new',
  subjectEdit: (id: string) => `/school/subjects/edit?id=${id}`,
  syllabus: '/school/syllabus',
  syllabusNew: '/school/syllabus/new',
  syllabusEdit: (id: string) => `/school/syllabus/edit?id=${id}`,
  materials: '/school/materials',
  materialsNew: '/school/materials/new',
  materialsEdit: (id: string) => `/school/materials/edit?id=${id}`,
  homework: '/school/homework',
  homeworkNew: '/school/homework/new',
  homeworkEdit: (id: string) => `/school/homework/edit?id=${id}`,
  timetable: '/school/timetable',
  timetableNew: '/school/timetable/new',
  timetableView: (id: string) => `/school/timetable?id=${id}`,
  timetableEdit: (id: string) => `/school/timetable/edit?id=${id}`,
  timetableEmployee: '/school/timetable/employee',
  timetableSession: '/school/timetable/session',
  subjectTeacherMap: '/school/subject-teacher-map',
  students: '/students',
  staffs: '/staffs',
  staffNew: '/staffs/create-new',
  staffView: (id: string) => `/staffs?id=${id}`,
  staffEdit: (id: string) => `/staffs?id=${id}&edit=true`,
  parents: '/parents',
  financeSetup: '/finance/setup',
  financeLedger: '/finance/ledger',
  salary: '/hr/salary',
} as const;
