export const PARENTS_PAGE = {
  title: 'Parents',
  addButton: 'Add Parent',
  bulkImport: 'Bulk Import',
  downloadTemplate: 'Download Template',
  table: {
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
    occupation: 'Occupation',
    status: 'Status',
    actions: 'Actions',
  },
  empty: 'No parents found.',
  form: {
    title: 'Add Parent',
    firstName: 'First Name *',
    lastName: 'Last Name',
    email: 'Email',
    dialCode: 'Dial Code',
    phone: 'Phone',
    occupation: 'Occupation',
    submit: 'Add Parent',
    cancel: 'Cancel',
  },
  editForm: {
    title: 'Edit Parent',
    submit: 'Save Changes',
    cancel: 'Cancel',
  },
  bulkImportForm: {
    title: 'Bulk Import Parents',
    file: 'Excel File *',
    submit: 'Import',
    cancel: 'Cancel',
  },
  linkStudentForm: {
    title: 'Link Student',
    studentId: 'Student ID *',
    submit: 'Link',
    cancel: 'Cancel',
  },
  placeholders: {
    firstName: 'Ramesh',
    lastName: 'Kumar',
    email: 'parent@example.com',
    dialCode: '+91',
    phone: '9876543210',
    occupation: 'Engineer',
    studentId: 'Student ID',
  },
} as const;
