export const SUBJECTS_PAGE = {
  title: 'Subjects',
  addButton: 'Add Subject',
  empty: 'No subjects found.',
  table: {
    name: 'Name',
    code: 'Code',
    displayOrder: 'Order',
    totalMarks: 'Total Marks',
    passingMarks: 'Passing Marks',
    elective: 'Elective',
    enabled: 'Enabled',
    actions: 'Actions',
  },
  form: {
    createTitle: 'Add New Subject',
    editTitle: 'Edit Subject',
    name: 'Name *',
    code: 'Subject Code',
    displayOrder: 'Display Order',
    totalMarks: 'Total Marks',
    passingMarks: 'Passing Marks',
    isElective: 'Elective',
    isActive: 'Enabled',
    submit: 'Create Subject',
    update: 'Save Changes',
    cancel: 'Cancel',
  },
  placeholders: {
    name: 'Enter Name',
    code: 'Enter Subject Code',
    displayOrder: '0',
    totalMarks: '100',
    passingMarks: '0',
  },
} as const;
