export const SYLLABUS_PAGE = {
  title: 'Syllabus',
  addButton: 'Add Syllabus',
  empty: 'No syllabus found.',
  table: {
    title: 'Title',
    class: 'Class',
    session: 'Session',
    enabled: 'Enabled',
    actions: 'Actions',
  },
  form: {
    createTitle: 'Create Syllabus',
    editTitle: 'Edit Syllabus',
    session: 'Session',
    class: 'Class *',
    title: 'Title *',
    content: 'Syllabus Content',
    isEnabled: 'Enabled',
    attachments: 'Syllabus File Attachment',
    attachmentsHint: 'jpg, png, pdf file accepted and Max 2MB each',
    submit: 'Create Syllabus',
    update: 'Save Changes',
    cancel: 'Cancel',
  },
  placeholders: {
    title: 'Enter Title',
    content: 'Type something',
    selectSession: 'Select Session',
    selectClass: 'Select Class',
  },
  attachmentTable: {
    fileName: 'File Name',
    status: 'Status',
    preview: 'Preview',
    view: 'Download / View',
    remove: 'Remove',
  },
} as const;
